### ISSUE TITLE
Horizons fetching include comet mag and slope values M/K 1/2

### ISSUE THREAD

**Issue by ysBach** [Caltech-IPAC/kete#150]
Currently `kete.horizons.fetch_known_orbit_data` has [hard-coded `fields`](https://github.com/Caltech-IPAC/kete/blob/72b86ffc84e0586c8bfedc46bbb2cdc28b67fc69/src/kete/horizons.py#L469).

In case people have slightly different needs (e.g., comet magnitudes, sort only a fraction of objects), how about make at least `fields` as an optional argument? (Full customizability doesn't seem to be necessary atm...)

**Comment by dahlend** [comment]
Yeah those fields are hard coded somewhat intentionally. Since Kete caches this file, having custom fields means having to find a clean way to deal with the currently cached file (IE: Do the contents of it get checked to see if the columns match? Do you always load what is there? etc etc). There are a few ways to handle that, but all of them that I can think of mean quite a bit of complexity, or potential for unexpected behavior for a user. 

I am open to adding more columns, but I have mixed opinion of making it fully customizable for this reason. I am assuming you would be interested in something like the M/K values for calculated expected comet fluxes? 
There exists some of the code for estimating comet fluxes [here](https://caltech-ipac.github.io/kete/api/flux.html#kete.flux.comet_apparent_mags), so I am considering adding support for those columns, as I believe we will need them for NEOS as well.

**Comment by dahlend** [comment]
I am going to update this to specify the inclusion of the M/K 1/2 values, if there are other ones you would like please let me know.

**Comment by ysBach** [comment]
Thanks @dahlend for taking a look into this! And sorry for being late.

I’ve completed a demonstration for SPHEREx without comet magnitudes (no magnitude calculation when the H column is NaN). Based on your feedback regarding design, I feel it might not be an essential part to get M/K 1/2 by default. These columns will be NaN for 99+% of the rows. A more effective approach might be that we (SPHEREx) flag any pixel with expected mag=NaN (i.e., mostly comets) as that will be only a small fraction of SSOs in FoV.

I’m awaiting input from @phanicode and/or the IPAC side, though it may take a few days as I only reached out to them today. At the moment, I have no objection to your approach (either no update or add M/K 1/2 and maybe the PC parameter). Thanks again for taking a look into this!
